#ifndef UCOS2_C66X_INTC_H
#define UCOS2_C66X_INTC_H

#include <types.h>

#define INTC_EVENT_TIMER_1  63
#define INTC_EVENT_TIMER_2  64
#define INTC_EVENT_TIMER_3  64
#define INTC_EVENT_TIMER_4  66
#define INTC_EVENT_TIMER_5  67
#define INTC_EVENT_TIMER_6  68
#define INTC_EVENT_TIMER_7  69
#define INTC_EVENT_TIMER_8  70
#define INTC_EVENT_TIMER_9  71
#define INTC_EVENT_TIMER_10 72
#define INTC_EVENT_TIMER_11 73

#define INTC_EVENT_XMC 110

#define INTC_EVENT_TASK_TIMER INTC_EVENT_TIMER_5
#define INTC_EVENT_PART_TIMER INTC_EVENT_TIMER_6

#define INTC_EVENT_MAILBOX 52

void intc_init(void);

void intc_event_clear(u32 eventId);

#endif //UCOS2_C66X_INTC_H
